### ISSUE TITLE
Create an installer for arch (AUR)

### ISSUE THREAD

**Issue by wuniversales** [carlelieser/flixerr#13]
Hi,
I would like an installer for aur to be available.
https://aur.archlinux.org/
Thanks greetings

**Comment by carlelieser** [comment]
@wuniversales I will look into this, thanks!

**Comment by DanielValahul** [comment]
I think an appimage (https://appimage.org) would be a better idea since it would solve the distribution problem across all major distros.

**Comment by carlelieser** [comment]
@DanielValahul I totally agree, this should be the next step.
