### ISSUE TITLE
[Bug] Subtitle encoder is not rendering the characters correctly

### ISSUE THREAD

**Issue by cccruzr** [carlelieser/Flixerr#14]
It seems that the subtitles encoder doesn't display the special characters of spanish language, such as ¿ ¡  á é í ó ú ñ

![](https://drive.google.com/uc?id=15r8xITFZhwECvFZ69AbPL7BMD0xaqGqv)

**Comment by carlelieser** [comment]
Fixed this in update 1.5.3!

**Comment by cccruzr** [comment]
@carlelieser Thanks a lot! Happy new year!
