### ISSUE TITLE
Fails to install in Debian Buster

### ISSUE THREAD

**Issue by codefan-byte** [carlelieser/flixerr#15]
Describe the bug

Installing the .deb package under debian testing (bullseye) or stable (buster) fails due to not installable dependency to gir1.2-gnomekeyring-1.0 .
libgnome-keyring is deprecated and it's use strongly discouraged [1]; hence gir1.2-gnomekeyring1.0 was removed in debian buster.
The debian and GNOME teams recommend using libsecret/gir1.2-secret-1 [2] instead.

Steps to reproduce the behavior

use either debian buster/stable or debian bullseye/testing
dpkg --install flixerr_1.5.2_amd64.deb
apt --fix-missing install
Get error message that gir1.2-gnomekeyring-1.0 is not installable
Expected behavior
No deprecated libraries should be used.

Desktop
OS: Debian GNU/Linux
References
[1] https://gitlab.gnome.org/GNOME/libgnome-keyring/commit/6a5adea4aec93
[2] https://wiki.gnome.org/Projects/Libsecret

https://github.com/IsmaelMartinez/teams-for-linux/issues/208#issue-478333924

**Comment by carlelieser** [comment]
Thanks for opening this issue. I will fix this as soon as possible, currently don’t have a Linux machine to test this on.

**Comment by ProCommanderYT** [comment]
> @rondeo Thanks for opening this issue. I will fix this as soon as possible, currently don’t have a Linux machine to test this on.

Try Using a Vitual Machine Through Qemu or Virtualbox to set up a linux vm

**Comment by eramax** [comment]
Hi
The issue still exists 
![image](https://user-images.githubusercontent.com/542413/85203549-d86a9880-b30e-11ea-9adf-2c36c5462ce9.png)

Please update it and I will try to check again.
Regards

**Comment by carlelieser** [comment]
> 
> 
> Hi
> The issue still exists
> ![image](https://user-images.githubusercontent.com/542413/85203549-d86a9880-b30e-11ea-9adf-2c36c5462ce9.png)
> 
> Please update it and I will try to check again.
> Regards

Is this issue still present with the latest release?

**Comment by carlelieser** [comment]
Closing this issue because our appimage stuff should take care of this. Feel free to open this back up if you encounter this again.
