### ISSUE TITLE
Integrating PopcornAPI in Flixerr 

### ISSUE THREAD

**Issue by RadGade** [carlelieser/Flixerr#19]
We should start integrating this [PopcornAPI ](https://popcornofficial.docs.apiary.io/#)as it guarantees working magnet links, also we can use this issue to track the progress of implementing this.

**Comment by carlelieser** [comment]
> 
> 
> We should start integrating this [PopcornAPI ](https://popcornofficial.docs.apiary.io/#)as it guarantees working magnet links, also we can use this issue to track the progress of implementing this.

I completely agree. This would be a great addition to the platform. I wouldn't use this for movie info like banners, or poster images though, but definitely for torrent fetching. If it works well enough we can forgo the torrent select dialog altogether.

**Comment by RadGade** [comment]
cool I also added a PiP view for the player and a watch later section, i am gonna push the changes sometime today

**Comment by carlelieser** [comment]
@RadGade As of version 1.5.5 this feature has been added! Thank you so much for suggesting it!
