### ISSUE TITLE
Rebuilding the player with WASM 

### ISSUE THREAD

**Issue by RadGade** [carlelieser/flixerr#28]
I was thinking to better optimize our player we could rebuild the whole player component with web assembly. This would take some time to implement so we can aim to push it out at one of the major releases. Also I love working on this project

**Comment by carlelieser** [comment]
@RadGade can you explain a little more? I’m not quite familiar with web assembly

**Comment by RadGade** [comment]
Like for example live transcoding would be much faster and efficient with wasm cuz it compiles down to native code

**Comment by carlelieser** [comment]
If you can implement that go right ahead!

**Comment by carlelieser** [comment]
After reviewing what it would actually take to accomplish this, I've concluded this is a huge undertaking and not necessarily worth our time as of right now. We might want to do this in the future, but I'm closing this for now to focus on other improvements.
