### ISSUE TITLE
Not working after building

### ISSUE THREAD

**Issue by santiagoworkana** [carlelieser/Flixerr#29]
Hello, can you please let me know if I'm doing it right? I jut generate the window unpacked but when i run it it stay white! not working at all.
To generate te unpacked i did sudo npm run publish I'm missing something?

Thanks,

**Comment by carlelieser** [comment]
try running `npm run compile` and then `npm run build` also make sure you're not building it with develop mode on.

**Comment by RadGade** [comment]
@carlelieser have you released the new version over auto-update

**Comment by carlelieser** [comment]
@RadGade No not yet. Unfortunately I don't have a Mac right now to make the mac os build and I want to release them all together

**Comment by carlelieser** [comment]
@santiagoworkana I just fixed this! It had to do with babel-polyfill. I moved it over from devDependencies to dependencies. Do a pull and you should be good to go.

**Comment by snisnik** [comment]
@carlelieser I'm testing and i tried to run the linux unpacked and the windows keeps white.
But when running with npm start it works just fine.
Any ideas? 

Thanks

**Comment by carlelieser** [comment]
@snisnik Try doing a git pull. I just pushed up some changes.
