### ISSUE TITLE
Please add a download button

### ISSUE THREAD

**Issue by ProCommanderYT** [carlelieser/Flixerr#33]
Could you please add a download button in the menu when u click a movie or TV show

Edit: Maybe also a downloads page to play the downloads from

**Comment by carlelieser** [comment]
@ProCommanderYT The reason I never added that before was because of the legality of that feature. Flixerr is already on thin ice for streaming movie torrents and adding the ability to actually keep these torrents on a user's computer is not something I really wanna get into it.
