### ISSUE TITLE
[Feature Request] Chromecast support

### ISSUE THREAD

**Issue by santiagoworkana** [carlelieser/Flixerr#36]
A cool feature would be to be able to cast to a chromecast to avoid using an HDMI cable!

**Comment by ProCommanderYT** [comment]
This sounds like a great idea

**Comment by RadGade** [comment]
@santiagoworkana @ProCommanderYT  I am almost done with it, its taking a bit cuz I have also added support for airplay and dLan which can be used to cast to a xbox one

**Comment by carlelieser** [comment]
I'm happy to say this feature request is now part of Flixerr!  #43
