### ISSUE TITLE
Movie that never load

### ISSUE THREAD

**Issue by santiagoworkana** [carlelieser/Flixerr#38]
There are a bunch of movies that after you click play never load.
This i becaue of not many seeds? Maybe is a way to identify those and not list them?

**Comment by santiagoworkana** [comment]
Today I'm seeing that i can't load any movie. 
I can play only movies that i started to watch in the past. With new movies I get only to looking in the universe... but never to generating conection.

Anyone know why could this be?

**Comment by RadGade** [comment]
One of the main apis has gone down

**Comment by RadGade** [comment]
@santiagoworkana I have pushed a pull request with an updated api

**Comment by carlelieser** [comment]
Yeah with the pull request from @RadGade and the most recent update, this issue should be fixed. Feel free to reopen if this issue persists.
