### ISSUE TITLE
Integration with bloom.sh Bitflow

### ISSUE THREAD

**Issue by antoninadert** [carlelieser/flixerr#5]
Hello, I just stumbled upon your project, I open this issue because I as well discovered another interesting project (bloom's bitflow) last week and the integration of both felt pretty obvious to me, so I am just doing the link. You can close the issue if you think it is not relevant.

Bitflow enables user to download torrent link on Bloom's cloud provider (30Go free) so this seems like a math made in heaven if I could connect to this service instead of having to download the torrent on my machine.

This is especially true since I will not need a VPN to protect myself. 
In France we have Hadopi who can check our IP address and can sue us if we download torrents and this is a real problem. 

Using this cloud provider, torrent is used on a cloud server and I just need to direct download the data in the end, so it is untrackable regarding to this Hadopi entity.

I wonder how far the integration can go but this looks like a solid evolution option.

https://bloom.sh/bitflow
https://gitlab.com/bloom42/bitflow

**Comment by carlelieser** [comment]
Hey, thanks for opening this issue, it seems like a really interesting idea. I will definitely be looking into this. I think the most difficult part would have to be implementing it unless they have some sort of API to interact with it, I’ll have to figure that out. Thanks for sharing!

**Comment by antoninadert** [comment]
I would try to contact the author of bloom who seem very open-minded to me, it may give him other ideas. I am glad I was able to help :) 
Cheers
