### ISSUE TITLE
Bug(White screen)

### ISSUE THREAD

**Issue by AnuragKC** [carlelieser/Flixerr#55]
ffs, upto v1.5.42,it works fine but 1.6 and 1.7 gets stucked on white screen,wtf is happening :(,I have just been using v1.5 for a long time

**Comment by ysfmrbt** [comment]
The same problem occurs for me with version 1.7

> 1.7 gets stucked on white screen

**Comment by JoelGarcia99** [comment]
> _The same problem occurs for me with version 1.7_
> 
> > 1.7 gets stucked on white screen
> 
> **Edit : Installing Apple's Bonjour SDK resolved the issue!**

How exactly did you install it, bro? I have installed the latest version and it does not work, the app still stuck on white screen

**Comment by carlelieser** [comment]
This is an issue with the latest installer update. v.1.7.0 uses a different installer that apparently doesn't bundle Bonjour with it. I will fix this in the next update.

**Comment by carlelieser** [comment]
Updated the version 1.7.0 release installer. It’ll download bonjour if needed which is the cause of the white screen (when bonjour is not installed)
