### ISSUE TITLE
Flixerr cannot open because of an error (MacOS Mojave)

### ISSUE THREAD

**Issue by Sin-** [carlelieser/Flixerr#6]
I just downloaded the stable release for MacOS and the app won't start.
It displays a system popup saying the app cannot launch because of an error.
Do you have any idea why?
I'll try to clone the repo and find the error when I have time

**Comment by carlelieser** [comment]
What version of Mac OS are you running? I believe this is an issue only on Mojave. Since I only have High Sierra on my Mac, I can’t compile a version compatible for Mojave.

**Comment by Sin-** [comment]
Indeed, I'm on Mojave!
Ok, I'll try to compile the source code in the coming days, I'll keep you posted

**Comment by carlelieser** [comment]
That would be great! If you want, you can wait for the next update this weekend and compile it then, or if you want to compile this version that’s fine too. Thanks!

**Comment by carlelieser** [comment]
Mojave support added in 1.5.0.
