### ISSUE TITLE
How do I start in linux

### ISSUE THREAD

**Issue by TheLox95** [carlelieser/Flixerr#7]
I'm using `Ubuntu 18.04.2 LTS (Bionic Beaver)`, I donwload the `flixerr-linux-x64-stable.zip` file on the release page but I cannot find instructions about how to install or run it

**Comment by carlelieser** [comment]
If you unzip the zip file and open up the executable it should work. Let me know if this doesn't work, I don't have Linux, but I will install if necessary.

**Comment by carlelieser** [comment]
Closing because I was able to compile it to an installable .deb file for Linux for the new update.
